### ISSUE TITLE
博主您好，我尝试复现您的程序，目前有一些疑问，想向您请教

### ISSUE THREAD

**Issue by XWJUN-aaa** [yuanphoenix/Bert-BiLSTM-CRF#2]
请问precision_score、recall_score、f1_score这三个数值一样的情况解决了吗，是否是是数据集的问题呢

**Comment by yuanphoenix** [comment]
是的，原理是https://www.zhihu.com/question/414824969
为了让它们不一样，你可以使用 macro 宏平均。我代码中是micro，改一下就好。

**Comment by XWJUN-aaa** [comment]
谢谢
